name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1 
      - name: Install dependencies
        run: npm ci
    #   - name: Run tests
    #     run: npm test
      # - name: Build for deployment (optional)
      #   if: ${{ github.ref == 'refs/heads/main' }}  # Only build on main branch push (adjust as needed)
      #   run: npm run build